
services:
  scada-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: scada-aijjo:latest
    container_name: scada-aijjo-service
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - MQTT_BROKER_URL=mqtt://broker.hivemq.com:1883
      - MQTT_USERNAME=
      - MQTT_PASSWORD=
    restart: unless-stopped
